import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { PageBodyBackground } from "@/components/page-body-background";
import Header from "@/components/sections/header";
import ViewCanvas from "@/components/view-canvas";
import Footer from "@/components/sections/footer";

const alpino = localFont({
  src: "../../public/fonts/Alpino-Variable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-alpino",
});

export const metadata: Metadata = {
  title: "Zingy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${alpino.variable} font-sans antialiased`}>
      <body className={`overflow-x-hidden bg-yellow-300`}>
        <PageBodyBackground />
        <Header />
        <main>
          {children}
          <ViewCanvas />
        </main>
        <Footer />
      </body>
    </html>
  );
}
